spring.application.name=cuentas
# Conexion a MySQL con variables de entorno
spring.datasource.url=${URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configuracion de loggin
logging.level.root=INFO
logging.level.gm.cuentas=INFO
logging.level.org.hibernate=WARN
logging.pattern.console=[%thread] %-5level: %logger{36} - %msg%n

#Banner de Spring al iniciar
spring.main.banner-mode=off

#Tema de primefaces (default tema = saga)
joinfaces.primefaces.theme=vela